name: Build and Publish Gem

on:
  push:
    tags:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.x'

      - name: Install dependencies
        run: bundle install

      - name: Build gem
        run: gem build iron_dome.gemspec

      - name: Publish gem
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: gem push iron_dome-*.gem
