name: Ruby

on:
  push:
    branches: [ "main" ]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run rubocop
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - name: Install dependencies
        run: |
          bundle install
        working-directory: ${{ github.workspace }}
      - name: Run Rubocop
        run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2', '3.3']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Install dependencies
      run: |
        bundle install
      working-directory: ${{ github.workspace }}
    - name: Run tests
      run: bundle exec rake

  security_sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Security SCA
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - name: Install dependencies
        run: |
          gem install iron_dome
        working-directory: ${{ github.workspace }}
      - name: Run IronDome
        run: iron_dome


  security_sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Security SAST
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - name: Install dependencies
        run: |
          gem install dawnscanner
          bundle install
          wget https://github.com/thesp0nge/dawnscanner_knowledge_base/releases/download/v20240116/kb.tar.gz
          tar -vzxf kb.tar.gz
          rm kb.tar.gz
          mkdir -p $HOME/dawnscanner/kb
          mv * $HOME/dawnscanner/kb/
        working-directory: ${{ github.workspace }}
      - name: Run dawn scanner
        run: |
          dawn scan ${{ github.workspace }}
